# Common settings
pulsar:
  brokerServiceUrl: pulsar://localhost:6650
  webServiceUrl: http://localhost:8080
  tenant: infinitic
  namespace: dev

# Workers settings
stateStorage: redis

redis:
  host: localhost
  port: 6379
  user:
  password:
  database: 0
